# WIP
name: olmo3-paper-eval

models:
  - name_or_path: meta-llama/Llama-3.1-8B
    gpus: 1
    # parallelism: 4

  - name_or_path: /weka/oe-training-default/ai2-llm/checkpoints/OLMo3-7B-swafix/step144000-hf/
    alias: olmo3-7b-swafix-144000
    gpus: 1
    # parallelism: 4

tasks:
  - olmo3:paper

cluster: ai2/ceres
budget: ai2/oe-base
workspace: ai2/olmo-3-evals
preemptible: true
timeout: 6h
