[engine]
cgroup_manager = "cgroupfs"
events_logger = "file"

[containers]
netns = "host"
userns = "host"
ipcns = "host"
utsns = "host"
cgroupns = "host"
cgroups = "disabled"
log_driver = "k8s-file"

[network]
network_backend = "slirp4netns"
